//Setor Requisições

###Post Cadastrar Setor
POST http://localhost:8080/setores
Content-Type: application/json

{
  "nome": "nome123",
  "descricao": "descricao_88f80a6f060b"
}

###Get todos setores
GET http://localhost:8080/setores

###Get setores Por ID
GET http://localhost:8080/setores/1

###Put Atualizar Setores
PUT http://localhost:8080/setores/1
Content-Type: application/json

{
  "nome": "nome_6994f8617e75",
  "descricao": "descricao_88f80a6f060b"
}

###Delete Setor Por ID
DELETE http://localhost:8080/setores/2

// Processos Requisições

###Post criar Processos
POST http://localhost:8080/processos
Content-Type: application/json

{
  "numero": "numero_466988a26f44",
  "nome": "nome_e21c5c97f113",
  "descricao": "descricao_a9f56f4fabec",
  "setorId": 4
}
###Get listar todos Processos
GET http://localhost:8080/processos

###Get Processos Por ID
GET http://localhost:8080/processos/1

###Get Processor Por Numero
GET http://localhost:8080/processos/numero/numero1

###Put Atualizar Processos
PUT http://localhost:8080/processos/1
Content-Type: application/json

{
  "numero": "numero_466988a26f44",
  "nome": "nome_e21c5c97f113",
  "descricao": "descricao_a9f56f4fabec",
  "setorId": 2
}

###Delete Processos Por ID
DELETE http://localhost:8080/processos/1

// Usuario Requisições

###Post Cadastrar Usuario
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "nome_6994f8617e75",
  "email": "email_88f80a6f060b",
  "senha": "senha_88f80a6f060b"
}

###Get Todos Usuarios
GET http://localhost:8080/usuarios

###Get Usuario Por ID
GET http://localhost:8080/usuarios/1

###PUT Atualizar Usuario
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "nome123",
  "email": "email123",
  "senha": "senha321"
}

###Delete Usuario Por ID
DELETE http://localhost:8080/usuarios/1

//Está meio incompleto a parte de Usuario, mas é só para ter uma ideia de como ficaria